post http://localhost:3000/api/catalogo/uploads
content-type: application/json

{
"name" : "galleta"

}

###
GET http://localhost:3000/api/catalogo/paises/all
content-type: application/json
x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xldXNlciI6ImFkbWluIiwibmFtZSI6IlJvZHJpZ29PbGFndWUiLCJlbWFpbCI6ImRvcmFkb0Bkb3JhZG8uY29tIiwiZXN0YWRvIjp0cnVlLCJpYXQiOjE2MTU1NzQzNzIsImV4cCI6MTYxNTY2MDc3Mn0.WISxDXznCiPqbjLzAOL-lHVS8db-hfV9DC_AJQSO1ds



###
get http://localhost:3000/api/catalogo/uploads
content-type: application/json



###
get http://localhost:3000/api/catalogo/uploads/excel/mis-catalogos
content-type: application/json
x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xldXNlciI6ImNsaWVudGUiLCJuYW1lIjoiUGFyYSBwcnVlYmFzIGVudmlvIGVtYWlsIiwiZW1haWwiOiJwcnVlYmFzLWZpbGF0ZWxpYUB5b3BtYWlsLmNvbSIsImVzdGFkbyI6dHJ1ZSwiaWF0IjoxNjE2NTI3NjkwLCJleHAiOjE2MTY2MTQwOTB9.2TBGwCr-zPrbp3eE5l1nu8DejH91-D75uCe16O3k5jw