post http://localhost:3000/api/catalogo/uploads
content-type: application/json

{
"name" : "galleta"

}

###
GET http://localhost:3000/api/catalogo/paises


http://localhost:3000/api/catalogo/paises/Colombia

http://localhost:3000/api/catalogo/paises/pid/:pid


http://localhost:3000/api/catalogo/paises/all



http://localhost:3000/api/catalogo/uploads/catalogo/cat