post https://filatelia.herokuapp.com/api/login
content-type: application/json

{
   
"email": "dorado@dorado.com",
"password": "22102281",
"roleuser": "admin"
}


###
post http://localhost:3000/api/login
content-type: application/json

{
   
"email": "dorado@dorado.com",
"password": "22102281"

}

###
post http://localhost:3000/api/login
content-type: application/json

{
   
"email": "cliente@cliente.com",
"password": "22102281"

}

###
//Para enviar emails
post https://api.filateliaperu.com/api/login
content-type: application/json

{
   
"email": "pruebas-filatelia@yopmail.com",
"password": "22102281"

}