post https://filatelia.herokuapp.com/api/catalogo/manco_list
content-type: application/json
x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xldXNlciI6ImFkbWluIiwibmFtZSI6IlJvZHJpZ29PbGFndWUiLCJlbWFpbCI6ImRvcmFkb0Bkb3JhZG8uY29tIiwiZXN0YWRvIjp0cnVlLCJpYXQiOjE2MTU1NzgxMzEsImV4cCI6MTYxNTY2NDUzMX0.1EtuxCoBw5q-0ykktWJ7jC43Eu7XGIbSkOhLVL0KDbQ

{
"id_estampilla":[ "604bc1fca6161a144c5484e2", "604bc1fca6161a144c5484e3" ]
}

###
get https://filateliab.doubleflyindustries.com/api/catalogo/manco_list/listar/60417ba2f37c05074c85ddf6
content-type: application/json

{

}
###
post http://localhost:3000/api/catalogo/manco_list/listar
content-type: application/json
x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xldXNlciI6ImFkbWluIiwibmFtZSI6IlJvZHJpZ29PbGFndWUiLCJlbWFpbCI6ImRvcmFkb0Bkb3JhZG8uY29tIiwiZXN0YWRvIjp0cnVlLCJpYXQiOjE2MTU0MDQwMzMsImV4cCI6MTYxNTQ5MDQzM30.Mv2NUDnGzpmpAsTxakORhG__9X0V6k9nNmn2E9PmfnM

{

}
