post https://filatelia.herokuapp.com/api/usuarios
content-type: application/json
x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xldXNlciI6ImFkbWluIiwibmFtZSI6ImFkbWluaXN0cmFkb3IiLCJlbWFpbCI6ImRvcmFkb0Bkb3JhZG8uY29tIiwiZXN0YWRvIjp0cnVlLCJpYXQiOjE2MTQ3MzM0NzMsImV4cCI6MTYxNDgxOTg3M30.lTZ45EORDeso5YdkUbeHeQh8-szlgF-x4Xo5C3EC3qg

{
"name" : "prueba para registro",
"email": "dorado@dorado.cort",
"password": "22102281",
"roleuser": "admin"
}
