post http://localhost:3000/api/usuarios
content-type: application/json
x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xldXNlciI6ImNsaWVudGUiLCJuYW1lIjoiQ2xpZW50ZSBub3JtYWwiLCJlbWFpbCI6ImNsaWVudGVAZ21haWwuY29tIiwiZXN0YWRvIjp0cnVlLCJpYXQiOjE2MTQ1Mjc1NzUsImV4cCI6MTYxNDYxMzk3NX0.3FyPfqzz-ACtSbfYLixIYjn-k6uxUxZTeBXKNfkETV4

{
"name" : "administrador",
"email": "dorado@dorado.com",
"password": "22102281",
"roleuser": "admin"
}
